### PR TITLE
Change Domain to IP in `API_URL`

### LINKED ISSUE #448: --server doesnt work when pihole is running locally
**Describe the bug**
running `./padd.sh --server 192.168.178.88 --secret shh` displays information on the pihole running locally
**To Reproduce**
I have pihole running locally and my user is part of the `pihole` group.
When running `./padd.sh --server 192.168.178.88 --secret  shh` i get information displayed about the local pihole not the one on .88
The ip needs to be running pihole, for example 
`./padd.sh --server 192.168.178.89 --secret shh` will result padd on getting stuck on the loading screen.

**Expected behavior**
Display information about 192.168.178.88

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by darkexplosiveqwx**
## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

Fixes #448

**How does this PR accomplish the above?:**

This changes API_URL to be `https://192.160.0.1:443/api/` instead of `https://pi.hole:443/api/` by taking the server specified with `--server`. 
This fixes the client not using the pihole its PADDing to a DNS since `webserver.domain` doesnt need to be resolved anymore.
Additionally this will lower the outgoing DNS requests for `webserver.domain`, why would we need to resolve that if we already know the ip of the server.
When specifying a hostname with `--server`, it was already checked in the beginning that the hostname is avalible via the systems DNS. (with `cmdResult="$(dig +short chaos txt domain.api.ftl @"${SERVER}" 2>&1; echo $?)"`)

**Link documentation PRs if any are needed to support this PR:**

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
I would still keep the IPv4/6 separation to maintain readability.

```
            # substitute everything between '//' and ':' with $SERVER             
            case "$SERVER" in
                *:*)
                    # Add square brackets for IPv6 (as recommended by RFC2732)
                    API_URL="$(echo "$API_URL" | sed 's/\/\/.*:/\/\/\[$SERVER\]:/')";;
                *)
                    API_URL="$(echo "$API_URL" | sed 's/\/\/.*:/\/\/$SERVER:/')";;
            esac
```

File: padd.sh [hunk 1]
```diff
@@ -137,6 +137,21 @@ TestAPIAvailability() {
         API_URL="${API_URL%\"}"
         API_URL="${API_URL#\"}"
 
+        # If $SERVER is user-specified by IP, the returned API_URL might contain a domain which can't be resolved by the host
+        # Therefore, we substitute the domain with the IP
+        if [ -n "$SERVER" ]; then
```
Comment (yubiuser) [inline padd.sh:142]: Do you think we should add another check if the `$SERVER` is actually an IP? It might be an domain already, so we could skip the whole substitution.

**Review by yubiuser — COMMENTED** [review]
You `sed` RegEx gave me a headache... ;-)

File: padd.sh (hunk 1 above)
Comment (darkexplosiveqwx) [reply padd.sh:142]: I thought about this, but if it's an hostname it's guaranteed to be resolvable due to the resolution of `domain.api.ftl` in the beginning. The actual domain might still not be resolvable.

In my setup both Pis use `pi.hole`
On my Desktop I access my secondary Pi with the hostname (`blueberrypi`) (Main Pi is DNS Server and has CForwarding). In this case blueberrypi works well. `pi.hole` would always resolve to the main Pi.

I don't think checking for the hostname is necessary and we can just replace the domain with the hostname.

Comment (yubiuser) [reply padd.sh:142]: Ok, convinced.

**Review by yubiuser — COMMENTED** [review]
Please squash down all commits, then this can be merged

**Review by yubiuser — APPROVED** [review]
